# Generated by Django 6.0.4 on 2026-05-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_ingreso',
            field=models.DateTimeField(verbose_name='Fecha de Ingreso'),
        ),
    ]
